### ISSUE TITLE
hero-animation: toPage is undefined!

### ISSUE THREAD

**Issue by mandrej** [supachailllpay/photo-gallery#1]
Your gallery is exactly what I want, but when click on grid image I get black page with navigation and error:
hero-animation: toPage is undefined!

Please help!

**Comment by supachailllpay** [comment]
Hi mandrej, sorry for my late reply. This project is too old. I'm not sure what's cause of this problem but it seems to disappear (for now) and it still has some bug. For quick fix I change some code in photo-gallery-page.html to

``` javascript
factoryImpl: function (content) {
  this.content = content;
},

attached: function () {
  this.appendChild(this.content);
}
```

I hope this help, thank you.
