### ISSUE TITLE
Add keyboard support

### ISSUE THREAD

**Issue by alejost848** [supachailllpay/photo-gallery#13]
It would be great to have keyboard support when viewing the images to cycle through them using the arrow keys. It could use the [`iron-a11y-keys`](https://www.webcomponents.org/element/PolymerElements/iron-a11y-keys) element and make a call to the `previous()` and `next()` functions on every left/right arrow press.

I can make a pull request if this functionality is desired.

**Comment by supachailllpay** [comment]
Yes, absolutely!
